name: DataDash QA Automation

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Playwright
        run: |
          pip install playwright
          python -m playwright install --with-deps

      - name: Run scraper 22ds2000010@ds.study.iitm.ac.in
        run: python scrape_tables.py